version: "3.4"

services:

  mongo:
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    labels:
      kompose.image-pull-policy: "Always"
      kompose.volume.size: 100Gi

  patent-manager:
    image: ${REGISTRY}patent-manager:${PATENT_MANAGER_VERSION:-latest}
    deploy:
      resources:
        reservations:
          cpus: '2'
        limits:
          memory: 2G
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE: prod
    labels:
      kompose.service.type: nodeport
      nginx.ingress.kubernetes.io/rewrite-target: /$$1
      kompose.image-pull-policy: "Always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      start_period: 60s

  nlp-processor:
    image: ${REGISTRY}nlp-processor:${PATENT_MANAGER_VERSION:-latest}
    deploy:
      replicas: 3
      resources:
        reservations:
          cpus: '2'
        limits:
          memory: 2G
    environment:
      - SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8081:8081
    labels:
      kompose.service.type: nodeport
      nginx.ingress.kubernetes.io/rewrite-target: /$$1
      kompose.image-pull-policy: "Always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      start_period: 60s

volumes:
  mongo-data:
