
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

spring:
  data:
    mongodb:
      database: basf
      host: mongo
  codec:
    max-in-memory-size: 20MB

server:
  port: 8082

nlp:
  hostname: nlp-processor
  port: 8081
  protocol: http
  ner-endpoint: api/document/entities
