spring:
  data:
    mongodb:
      host: mongo
  cloud:
    stream:
      kafka:
        binder:
          brokers: basf-kafka:9092
          zk-nodes: basf-zookeeper:2181

nlp:
  hostname: nlp-processor
