name: CI Pipeline

on:
  push:

jobs:

  publish-chart:
    name: Publish chart
    runs-on: ubuntu-18.04
    env:
      REGISTRY: rogomdi/
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Install kompose & helm
        run: |
          curl -L https://github.com/kubernetes-incubator/kompose/releases/download/v0.7.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          wget https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
          tar -zxvf helm-v3.4.2-linux-amd64.tar.gz
          mv linux-amd64/helm helm
      - name: Build chart
        run: |
          ./build-all.sh
          mkdir charts
          mv basf-test* charts/
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}